Allow lookup hostIPs by DNS
uber/buck-http-cache pull request #5
Opened 2016-11-11 02:15 UTC by zayhero

Currently `buck-http-cache` meed static host IPs (or address) to enable cluster mode, however, this not working well if we have dynamic hosts. For example, when we are using kubernetes to run multiple docker images, we don't know how many hosts we are going to use and the IP / domain name may change.

To solve the problem, the PR is introducing `dnsLookupAddress`, and use `DnsSrvResolver` to lookup all nodes for that particular DNS address.
For example, if we are running the server in kubernetes with port name `buck-http-cache-port` and service name `buck-http-cache`, we can use `_buck-http-cache-port._tcp.buck-http-cache` to lookup DNS. With that, we could save the effort to figure out all host IP / address and don't need zookeeper. 

Sample `standalone.yml`:

```
storeProviderConfig:
  config:
    multicastIP: 228.10.10.157
    multicastPort: 6734
    hostIPs:
    dnsLookupAddress: _buck-http-cache-port._tcp.buck-http-cache
    cacheMode: PARTITIONED
    cacheBackupCount: 1
    expirationTimeUnit: DAYS
    expirationTimeValue: 2
    atomicSequencereserveSize: 10000
    offHeapStorageSize: 40g # 40GB
```

2016-11-13 03:18 UTC, kageiit requested changes
Please add some tests as well. But looks good otherwise

2016-11-13 03:18 UTC, kageiit commented on cache/src/main/java/com/uber/buckcache/datastore/impl/ignite/IgniteConfigurationBuilder.java
> +    if (hasHostIPs && hasDNSLookupAddress) {
I dont think this should be a requirement. Any reason why we cannot add all the hosts specified via various means to the pool?

2016-11-14 21:49 UTC, dhaval2025 commented
other than the comment posted, it looks good. Btw Ignite also as a ZKBacked discovery mechanism. We can add that as a config option too

2016-11-14 21:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/buck-http-cache?pullRequest=5) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/buck-http-cache?pullRequest=5) before we can accept your contribution.<br/><hr/>**brian_zhang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2016-11-14 22:00 UTC, dhaval2025 approved these changes

2016-11-14 22:00 UTC, dhaval2025 commented on cache/src/main/java/com/uber/buckcache/datastore/impl/ignite/IgniteConfigurationBuilder.java
> +    if (hasHostIPs && hasDNSLookupAddress) {
we can allow users to provide both the options, only setup DNS if its specified. Correct me if I am wrong but specifying both (IPs and DNS lookup) should not affect anything..

2016-11-14 22:00 UTC, dhaval2025 commented on cache/src/main/java/com/uber/buckcache/datastore/impl/ignite/IgniteConfigurationBuilder.java
> +    if (hasHostIPs && hasDNSLookupAddress) {
nvm ... looks good

2016-11-14 22:00 UTC, merged